/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'pendingBookings' : bigint,
  'cancelledBookings' : bigint,
  'totalSpots' : bigint,
  'totalGuides' : bigint,
  'confirmedBookings' : bigint,
  'totalReviews' : bigint,
}
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'endDate' : string,
  'guideId' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'message' : string,
  'spotId' : string,
  'startDate' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'confirmed' : null };
export type ExternalBlob = Uint8Array;
export type FeeStatus = { 'paid' : null } |
  { 'unpaid' : null };
export interface NewTourGuide {
  'bio' : string,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'languages' : Array<string>,
  'available' : boolean,
  'pricePerDay' : bigint,
}
export interface NewTouristSpot {
  'name' : string,
  'description' : string,
  'isPrivate' : boolean,
  'category' : Type,
  'location' : string,
  'photos' : Array<ExternalBlob>,
}
export interface Review {
  'id' : string,
  'userId' : Principal,
  'authorName' : string,
  'comment' : string,
  'targetType' : { 'spot' : null } |
    { 'guide' : null },
  'rating' : bigint,
  'targetId' : string,
}
export type Time = bigint;
export interface TourGuide {
  'id' : string,
  'bio' : string,
  'status' : Type__1,
  'platformFee' : bigint,
  'feeStatus' : FeeStatus,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'languages' : Array<string>,
  'available' : boolean,
  'pricePerDay' : bigint,
}
export interface TouristSpot {
  'id' : string,
  'status' : Type__1,
  'platformFee' : bigint,
  'feeStatus' : FeeStatus,
  'name' : string,
  'description' : string,
  'isPrivate' : boolean,
  'category' : Type,
  'location' : string,
  'photos' : Array<ExternalBlob>,
}
export type Type = { 'nature' : null } |
  { 'museum' : null } |
  { 'city' : null } |
  { 'historical' : null } |
  { 'beach' : null };
export type Type__1 = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<
    [string, { 'spot' : null } | { 'guide' : null }, bigint, string, string],
    Review
  >,
  'addTourGuide' : ActorMethod<[NewTourGuide], TourGuide>,
  'approveTourGuide' : ActorMethod<[string], TourGuide>,
  'approveTouristSpot' : ActorMethod<[string], TouristSpot>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, string],
    Booking
  >,
  'createTouristSpot' : ActorMethod<[NewTouristSpot], TouristSpot>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'deleteTourGuide' : ActorMethod<[string], undefined>,
  'deleteTouristSpot' : ActorMethod<[string], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllApprovedSpots' : ActorMethod<[], Array<TouristSpot>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllGuides' : ActorMethod<[], Array<TourGuide>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllSpots' : ActorMethod<[], Array<TouristSpot>>,
  'getAvailableGuides' : ActorMethod<[], Array<TourGuide>>,
  'getBookingsByGuide' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByUser' : ActorMethod<[Principal], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGuidesWithPendingFees' : ActorMethod<[], Array<TourGuide>>,
  'getReviewsByTarget' : ActorMethod<[string], Array<Review>>,
  'getSpotsWithPendingFees' : ActorMethod<[], Array<TouristSpot>>,
  'getTouristSpotsByCategory' : ActorMethod<[Type], Array<TouristSpot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markGuideFeeAsPaid' : ActorMethod<[string], undefined>,
  'markSpotFeeAsPaid' : ActorMethod<[string], undefined>,
  'rejectTourGuide' : ActorMethod<[string], TourGuide>,
  'rejectTouristSpot' : ActorMethod<[string], TouristSpot>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[string, BookingStatus], Booking>,
  'updateTourGuide' : ActorMethod<[string, NewTourGuide], TourGuide>,
  'updateTouristSpot' : ActorMethod<[string, NewTouristSpot], TouristSpot>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];