/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'authorName' : IDL.Text,
  'comment' : IDL.Text,
  'targetType' : IDL.Variant({ 'spot' : IDL.Null, 'guide' : IDL.Null }),
  'rating' : IDL.Nat,
  'targetId' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const NewTourGuide = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'languages' : IDL.Vec(IDL.Text),
  'available' : IDL.Bool,
  'pricePerDay' : IDL.Nat,
});
export const Type__1 = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const FeeStatus = IDL.Variant({
  'paid' : IDL.Null,
  'unpaid' : IDL.Null,
});
export const TourGuide = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'status' : Type__1,
  'platformFee' : IDL.Nat,
  'feeStatus' : FeeStatus,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'languages' : IDL.Vec(IDL.Text),
  'available' : IDL.Bool,
  'pricePerDay' : IDL.Nat,
});
export const Type = IDL.Variant({
  'nature' : IDL.Null,
  'museum' : IDL.Null,
  'city' : IDL.Null,
  'historical' : IDL.Null,
  'beach' : IDL.Null,
});
export const TouristSpot = IDL.Record({
  'id' : IDL.Text,
  'status' : Type__1,
  'platformFee' : IDL.Nat,
  'feeStatus' : FeeStatus,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPrivate' : IDL.Bool,
  'category' : Type,
  'location' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'endDate' : IDL.Text,
  'guideId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'message' : IDL.Text,
  'spotId' : IDL.Text,
  'startDate' : IDL.Text,
});
export const NewTouristSpot = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isPrivate' : IDL.Bool,
  'category' : Type,
  'location' : IDL.Text,
  'photos' : IDL.Vec(ExternalBlob),
});
export const AdminStats = IDL.Record({
  'pendingBookings' : IDL.Nat,
  'cancelledBookings' : IDL.Nat,
  'totalSpots' : IDL.Nat,
  'totalGuides' : IDL.Nat,
  'confirmedBookings' : IDL.Nat,
  'totalReviews' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({ 'spot' : IDL.Null, 'guide' : IDL.Null }),
        IDL.Nat,
        IDL.Text,
        IDL.Text,
      ],
      [Review],
      [],
    ),
  'addTourGuide' : IDL.Func([NewTourGuide], [TourGuide], []),
  'approveTourGuide' : IDL.Func([IDL.Text], [TourGuide], []),
  'approveTouristSpot' : IDL.Func([IDL.Text], [TouristSpot], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Booking],
      [],
    ),
  'createTouristSpot' : IDL.Func([NewTouristSpot], [TouristSpot], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'deleteTourGuide' : IDL.Func([IDL.Text], [], []),
  'deleteTouristSpot' : IDL.Func([IDL.Text], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllApprovedSpots' : IDL.Func([], [IDL.Vec(TouristSpot)], ['query']),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllGuides' : IDL.Func([], [IDL.Vec(TourGuide)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAllSpots' : IDL.Func([], [IDL.Vec(TouristSpot)], ['query']),
  'getAvailableGuides' : IDL.Func([], [IDL.Vec(TourGuide)], ['query']),
  'getBookingsByGuide' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getBookingsByUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGuidesWithPendingFees' : IDL.Func([], [IDL.Vec(TourGuide)], ['query']),
  'getReviewsByTarget' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getSpotsWithPendingFees' : IDL.Func([], [IDL.Vec(TouristSpot)], ['query']),
  'getTouristSpotsByCategory' : IDL.Func(
      [Type],
      [IDL.Vec(TouristSpot)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markGuideFeeAsPaid' : IDL.Func([IDL.Text], [], []),
  'markSpotFeeAsPaid' : IDL.Func([IDL.Text], [], []),
  'rejectTourGuide' : IDL.Func([IDL.Text], [TourGuide], []),
  'rejectTouristSpot' : IDL.Func([IDL.Text], [TouristSpot], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [Booking], []),
  'updateTourGuide' : IDL.Func([IDL.Text, NewTourGuide], [TourGuide], []),
  'updateTouristSpot' : IDL.Func([IDL.Text, NewTouristSpot], [TouristSpot], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'authorName' : IDL.Text,
    'comment' : IDL.Text,
    'targetType' : IDL.Variant({ 'spot' : IDL.Null, 'guide' : IDL.Null }),
    'rating' : IDL.Nat,
    'targetId' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const NewTourGuide = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'languages' : IDL.Vec(IDL.Text),
    'available' : IDL.Bool,
    'pricePerDay' : IDL.Nat,
  });
  const Type__1 = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const FeeStatus = IDL.Variant({ 'paid' : IDL.Null, 'unpaid' : IDL.Null });
  const TourGuide = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'status' : Type__1,
    'platformFee' : IDL.Nat,
    'feeStatus' : FeeStatus,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'languages' : IDL.Vec(IDL.Text),
    'available' : IDL.Bool,
    'pricePerDay' : IDL.Nat,
  });
  const Type = IDL.Variant({
    'nature' : IDL.Null,
    'museum' : IDL.Null,
    'city' : IDL.Null,
    'historical' : IDL.Null,
    'beach' : IDL.Null,
  });
  const TouristSpot = IDL.Record({
    'id' : IDL.Text,
    'status' : Type__1,
    'platformFee' : IDL.Nat,
    'feeStatus' : FeeStatus,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPrivate' : IDL.Bool,
    'category' : Type,
    'location' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'endDate' : IDL.Text,
    'guideId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'message' : IDL.Text,
    'spotId' : IDL.Text,
    'startDate' : IDL.Text,
  });
  const NewTouristSpot = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isPrivate' : IDL.Bool,
    'category' : Type,
    'location' : IDL.Text,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const AdminStats = IDL.Record({
    'pendingBookings' : IDL.Nat,
    'cancelledBookings' : IDL.Nat,
    'totalSpots' : IDL.Nat,
    'totalGuides' : IDL.Nat,
    'confirmedBookings' : IDL.Nat,
    'totalReviews' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({ 'spot' : IDL.Null, 'guide' : IDL.Null }),
          IDL.Nat,
          IDL.Text,
          IDL.Text,
        ],
        [Review],
        [],
      ),
    'addTourGuide' : IDL.Func([NewTourGuide], [TourGuide], []),
    'approveTourGuide' : IDL.Func([IDL.Text], [TourGuide], []),
    'approveTouristSpot' : IDL.Func([IDL.Text], [TouristSpot], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Booking],
        [],
      ),
    'createTouristSpot' : IDL.Func([NewTouristSpot], [TouristSpot], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'deleteTourGuide' : IDL.Func([IDL.Text], [], []),
    'deleteTouristSpot' : IDL.Func([IDL.Text], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllApprovedSpots' : IDL.Func([], [IDL.Vec(TouristSpot)], ['query']),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllGuides' : IDL.Func([], [IDL.Vec(TourGuide)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAllSpots' : IDL.Func([], [IDL.Vec(TouristSpot)], ['query']),
    'getAvailableGuides' : IDL.Func([], [IDL.Vec(TourGuide)], ['query']),
    'getBookingsByGuide' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getBookingsByUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGuidesWithPendingFees' : IDL.Func([], [IDL.Vec(TourGuide)], ['query']),
    'getReviewsByTarget' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getSpotsWithPendingFees' : IDL.Func([], [IDL.Vec(TouristSpot)], ['query']),
    'getTouristSpotsByCategory' : IDL.Func(
        [Type],
        [IDL.Vec(TouristSpot)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markGuideFeeAsPaid' : IDL.Func([IDL.Text], [], []),
    'markSpotFeeAsPaid' : IDL.Func([IDL.Text], [], []),
    'rejectTourGuide' : IDL.Func([IDL.Text], [TourGuide], []),
    'rejectTouristSpot' : IDL.Func([IDL.Text], [TouristSpot], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Text, BookingStatus], [Booking], []),
    'updateTourGuide' : IDL.Func([IDL.Text, NewTourGuide], [TourGuide], []),
    'updateTouristSpot' : IDL.Func(
        [IDL.Text, NewTouristSpot],
        [TouristSpot],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };