/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface NewTourGuide {
    bio: string;
    name: string;
    profilePhoto?: ExternalBlob;
    languages: Array<string>;
    available: boolean;
    pricePerDay: bigint;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface TourGuide {
    id: string;
    bio: string;
    status: Type__1;
    platformFee: bigint;
    feeStatus: FeeStatus;
    name: string;
    profilePhoto?: ExternalBlob;
    languages: Array<string>;
    available: boolean;
    pricePerDay: bigint;
}
export interface AdminStats {
    pendingBookings: bigint;
    cancelledBookings: bigint;
    totalSpots: bigint;
    totalGuides: bigint;
    confirmedBookings: bigint;
    totalReviews: bigint;
}
export interface NewTouristSpot {
    name: string;
    description: string;
    isPrivate: boolean;
    category: Type;
    location: string;
    photos: Array<ExternalBlob>;
}
export interface Booking {
    id: string;
    status: BookingStatus;
    endDate: string;
    guideId: string;
    userId: Principal;
    createdAt: Time;
    message: string;
    spotId: string;
    startDate: string;
}
export interface TouristSpot {
    id: string;
    status: Type__1;
    platformFee: bigint;
    feeStatus: FeeStatus;
    name: string;
    description: string;
    isPrivate: boolean;
    category: Type;
    location: string;
    photos: Array<ExternalBlob>;
}
export interface Review {
    id: string;
    userId: Principal;
    authorName: string;
    comment: string;
    targetType: Variant_spot_guide;
    rating: bigint;
    targetId: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    pending = "pending",
    confirmed = "confirmed"
}
export enum FeeStatus {
    paid = "paid",
    unpaid = "unpaid"
}
export enum Type {
    nature = "nature",
    museum = "museum",
    city = "city",
    historical = "historical",
    beach = "beach"
}
export enum Type__1 {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_spot_guide {
    spot = "spot",
    guide = "guide"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addReview(targetId: string, targetType: Variant_spot_guide, rating: bigint, comment: string, authorName: string): Promise<Review>;
    addTourGuide(newGuide: NewTourGuide): Promise<TourGuide>;
    approveTourGuide(id: string): Promise<TourGuide>;
    approveTouristSpot(id: string): Promise<TouristSpot>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBooking(guideId: string, spotId: string, startDate: string, endDate: string, message: string): Promise<Booking>;
    createTouristSpot(newSpot: NewTouristSpot): Promise<TouristSpot>;
    deleteReview(reviewId: string): Promise<void>;
    deleteTourGuide(id: string): Promise<void>;
    deleteTouristSpot(id: string): Promise<void>;
    getAdminStats(): Promise<AdminStats>;
    getAllApprovedSpots(): Promise<Array<TouristSpot>>;
    getAllBookings(): Promise<Array<Booking>>;
    getAllGuides(): Promise<Array<TourGuide>>;
    getAllReviews(): Promise<Array<Review>>;
    getAllSpots(): Promise<Array<TouristSpot>>;
    getAvailableGuides(): Promise<Array<TourGuide>>;
    getBookingsByGuide(guideId: string): Promise<Array<Booking>>;
    getBookingsByUser(userId: Principal): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGuidesWithPendingFees(): Promise<Array<TourGuide>>;
    getReviewsByTarget(targetId: string): Promise<Array<Review>>;
    getSpotsWithPendingFees(): Promise<Array<TouristSpot>>;
    getTouristSpotsByCategory(category: Type): Promise<Array<TouristSpot>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markGuideFeeAsPaid(guideId: string): Promise<void>;
    markSpotFeeAsPaid(spotId: string): Promise<void>;
    rejectTourGuide(id: string): Promise<TourGuide>;
    rejectTouristSpot(id: string): Promise<TouristSpot>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBookingStatus(bookingId: string, newStatus: BookingStatus): Promise<Booking>;
    updateTourGuide(id: string, updatedGuide: NewTourGuide): Promise<TourGuide>;
    updateTouristSpot(id: string, updatedSpot: NewTouristSpot): Promise<TouristSpot>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, ExternalBlob as _ExternalBlob, FeeStatus as _FeeStatus, NewTourGuide as _NewTourGuide, NewTouristSpot as _NewTouristSpot, Review as _Review, Time as _Time, TourGuide as _TourGuide, TouristSpot as _TouristSpot, Type as _Type, Type__1 as _Type__1, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addReview(arg0: string, arg1: Variant_spot_guide, arg2: bigint, arg3: string, arg4: string): Promise<Review> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return from_candid_Review_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, to_candid_variant_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return from_candid_Review_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addTourGuide(arg0: NewTourGuide): Promise<TourGuide> {
        if (this.processError) {
            try {
                const result = await this.actor.addTourGuide(await to_candid_NewTourGuide_n12(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TourGuide_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTourGuide(await to_candid_NewTourGuide_n12(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TourGuide_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveTourGuide(arg0: string): Promise<TourGuide> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTourGuide(arg0);
                return from_candid_TourGuide_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTourGuide(arg0);
            return from_candid_TourGuide_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveTouristSpot(arg0: string): Promise<TouristSpot> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTouristSpot(arg0);
                return from_candid_TouristSpot_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTouristSpot(arg0);
            return from_candid_TouristSpot_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Booking_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Booking_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTouristSpot(arg0: NewTouristSpot): Promise<TouristSpot> {
        if (this.processError) {
            try {
                const result = await this.actor.createTouristSpot(await to_candid_NewTouristSpot_n34(this._uploadFile, this._downloadFile, arg0));
                return from_candid_TouristSpot_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTouristSpot(await to_candid_NewTouristSpot_n34(this._uploadFile, this._downloadFile, arg0));
            return from_candid_TouristSpot_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async deleteTourGuide(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTourGuide(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTourGuide(arg0);
            return result;
        }
    }
    async deleteTouristSpot(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTouristSpot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTouristSpot(arg0);
            return result;
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllApprovedSpots(): Promise<Array<TouristSpot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApprovedSpots();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApprovedSpots();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGuides(): Promise<Array<TourGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGuides();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGuides();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSpots(): Promise<Array<TouristSpot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSpots();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSpots();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableGuides(): Promise<Array<TourGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableGuides();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableGuides();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByGuide(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByGuide(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByGuide(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByUser(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByUser(arg0);
                return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByUser(arg0);
            return from_candid_vec_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGuidesWithPendingFees(): Promise<Array<TourGuide>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuidesWithPendingFees();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuidesWithPendingFees();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReviewsByTarget(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByTarget(arg0);
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByTarget(arg0);
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSpotsWithPendingFees(): Promise<Array<TouristSpot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpotsWithPendingFees();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpotsWithPendingFees();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTouristSpotsByCategory(arg0: Type): Promise<Array<TouristSpot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTouristSpotsByCategory(to_candid_Type_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTouristSpotsByCategory(to_candid_Type_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markGuideFeeAsPaid(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markGuideFeeAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markGuideFeeAsPaid(arg0);
            return result;
        }
    }
    async markSpotFeeAsPaid(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSpotFeeAsPaid(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSpotFeeAsPaid(arg0);
            return result;
        }
    }
    async rejectTourGuide(arg0: string): Promise<TourGuide> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTourGuide(arg0);
                return from_candid_TourGuide_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTourGuide(arg0);
            return from_candid_TourGuide_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectTouristSpot(arg0: string): Promise<TouristSpot> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTouristSpot(arg0);
                return from_candid_TouristSpot_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTouristSpot(arg0);
            return from_candid_TouristSpot_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateBookingStatus(arg0: string, arg1: BookingStatus): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n46(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Booking_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n46(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Booking_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTourGuide(arg0: string, arg1: NewTourGuide): Promise<TourGuide> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTourGuide(arg0, await to_candid_NewTourGuide_n12(this._uploadFile, this._downloadFile, arg1));
                return from_candid_TourGuide_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTourGuide(arg0, await to_candid_NewTourGuide_n12(this._uploadFile, this._downloadFile, arg1));
            return from_candid_TourGuide_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTouristSpot(arg0: string, arg1: NewTouristSpot): Promise<TouristSpot> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTouristSpot(arg0, await to_candid_NewTouristSpot_n34(this._uploadFile, this._downloadFile, arg1));
                return from_candid_TouristSpot_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTouristSpot(arg0, await to_candid_NewTouristSpot_n34(this._uploadFile, this._downloadFile, arg1));
            return from_candid_TouristSpot_n23(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FeeStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FeeStatus): FeeStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
async function from_candid_TourGuide_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TourGuide): Promise<TourGuide> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_TouristSpot_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TouristSpot): Promise<TouristSpot> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Type__1_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type__1): Type__1 {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    userId: Principal;
    authorName: string;
    comment: string;
    targetType: {
        spot: null;
    } | {
        guide: null;
    };
    rating: bigint;
    targetId: string;
}): {
    id: string;
    userId: Principal;
    authorName: string;
    comment: string;
    targetType: Variant_spot_guide;
    rating: bigint;
    targetId: string;
} {
    return {
        id: value.id,
        userId: value.userId,
        authorName: value.authorName,
        comment: value.comment,
        targetType: from_candid_variant_n11(_uploadFile, _downloadFile, value.targetType),
        rating: value.rating,
        targetId: value.targetId
    };
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    bio: string;
    status: _Type__1;
    platformFee: bigint;
    feeStatus: _FeeStatus;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    languages: Array<string>;
    available: boolean;
    pricePerDay: bigint;
}): Promise<{
    id: string;
    bio: string;
    status: Type__1;
    platformFee: bigint;
    feeStatus: FeeStatus;
    name: string;
    profilePhoto?: ExternalBlob;
    languages: Array<string>;
    available: boolean;
    pricePerDay: bigint;
}> {
    return {
        id: value.id,
        bio: value.bio,
        status: from_candid_Type__1_n17(_uploadFile, _downloadFile, value.status),
        platformFee: value.platformFee,
        feeStatus: from_candid_FeeStatus_n19(_uploadFile, _downloadFile, value.feeStatus),
        name: value.name,
        profilePhoto: record_opt_to_undefined(await from_candid_opt_n21(_uploadFile, _downloadFile, value.profilePhoto)),
        languages: value.languages,
        available: value.available,
        pricePerDay: value.pricePerDay
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _Type__1;
    platformFee: bigint;
    feeStatus: _FeeStatus;
    name: string;
    description: string;
    isPrivate: boolean;
    category: _Type;
    location: string;
    photos: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    status: Type__1;
    platformFee: bigint;
    feeStatus: FeeStatus;
    name: string;
    description: string;
    isPrivate: boolean;
    category: Type;
    location: string;
    photos: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        status: from_candid_Type__1_n17(_uploadFile, _downloadFile, value.status),
        platformFee: value.platformFee,
        feeStatus: from_candid_FeeStatus_n19(_uploadFile, _downloadFile, value.feeStatus),
        name: value.name,
        description: value.description,
        isPrivate: value.isPrivate,
        category: from_candid_Type_n25(_uploadFile, _downloadFile, value.category),
        location: value.location,
        photos: await from_candid_vec_n27(_uploadFile, _downloadFile, value.photos)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BookingStatus;
    endDate: string;
    guideId: string;
    userId: Principal;
    createdAt: _Time;
    message: string;
    spotId: string;
    startDate: string;
}): {
    id: string;
    status: BookingStatus;
    endDate: string;
    guideId: string;
    userId: Principal;
    createdAt: Time;
    message: string;
    spotId: string;
    startDate: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n32(_uploadFile, _downloadFile, value.status),
        endDate: value.endDate,
        guideId: value.guideId,
        userId: value.userId,
        createdAt: value.createdAt,
        message: value.message,
        spotId: value.spotId,
        startDate: value.startDate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spot: null;
} | {
    guide: null;
}): Variant_spot_guide {
    return "spot" in value ? Variant_spot_guide.spot : "guide" in value ? Variant_spot_guide.guide : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): Type__1 {
    return "pending" in value ? Type__1.pending : "approved" in value ? Type__1.approved : "rejected" in value ? Type__1.rejected : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    unpaid: null;
}): FeeStatus {
    return "paid" in value ? FeeStatus.paid : "unpaid" in value ? FeeStatus.unpaid : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nature: null;
} | {
    museum: null;
} | {
    city: null;
} | {
    historical: null;
} | {
    beach: null;
}): Type {
    return "nature" in value ? Type.nature : "museum" in value ? Type.museum : "city" in value ? Type.city : "historical" in value ? Type.historical : "beach" in value ? Type.beach : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n22(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TouristSpot>): Promise<Array<TouristSpot>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TouristSpot_n23(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n30(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TourGuide>): Promise<Array<TourGuide>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TourGuide_n15(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n9(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_NewTourGuide_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewTourGuide): Promise<_NewTourGuide> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_NewTouristSpot_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewTouristSpot): Promise<_NewTouristSpot> {
    return await to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    name: string;
    profilePhoto?: ExternalBlob;
    languages: Array<string>;
    available: boolean;
    pricePerDay: bigint;
}): Promise<{
    bio: string;
    name: string;
    profilePhoto: [] | [_ExternalBlob];
    languages: Array<string>;
    available: boolean;
    pricePerDay: bigint;
}> {
    return {
        bio: value.bio,
        name: value.name,
        profilePhoto: value.profilePhoto ? candid_some(await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.profilePhoto)) : candid_none(),
        languages: value.languages,
        available: value.available,
        pricePerDay: value.pricePerDay
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    description: string;
    isPrivate: boolean;
    category: Type;
    location: string;
    photos: Array<ExternalBlob>;
}): Promise<{
    name: string;
    description: string;
    isPrivate: boolean;
    category: _Type;
    location: string;
    photos: Array<_ExternalBlob>;
}> {
    return {
        name: value.name,
        description: value.description,
        isPrivate: value.isPrivate,
        category: to_candid_Type_n36(_uploadFile, _downloadFile, value.category),
        location: value.location,
        photos: await to_candid_vec_n38(_uploadFile, _downloadFile, value.photos)
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    nature: null;
} | {
    museum: null;
} | {
    city: null;
} | {
    historical: null;
} | {
    beach: null;
} {
    return value == Type.nature ? {
        nature: null
    } : value == Type.museum ? {
        museum: null
    } : value == Type.city ? {
        city: null
    } : value == Type.historical ? {
        historical: null
    } : value == Type.beach ? {
        beach: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_spot_guide): {
    spot: null;
} | {
    guide: null;
} {
    return value == Variant_spot_guide.spot ? {
        spot: null
    } : value == Variant_spot_guide.guide ? {
        guide: null
    } : value;
}
async function to_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n14(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
